from enum import Enum


class RoutingServiceType(str, Enum):
    OTHER = "OTHER"
    CHANGENOW = "CHANGENOW"
    CCTP = "CCTP"
    DIRECT_TRANSFER = "DIRECT_TRANSFER"


class PayOrderStatus(str, Enum):
    PENDING = "PENDING"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    EXECUTING_ORDER = "EXECUTING_ORDER"
    COMPLETED = "COMPLETED"
    REFUNDED = "REFUNDED"


class PayOrderMode(str, Enum):
    SALE = "SALE"
    DEPOSIT = "DEPOSIT"
